header_value code to be dynamic

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -7,7 +7,7 @@
 # Task 1: Configure Nginx on web-01 and web-02
 link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
 header_key="X-Served-By"
-header_value="\$hostname"
+header_value="$(hostname)"
 new_conf="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;\n\tadd_header $header_key $header_value;"
 location_error="location = /404.html {\n\t\troot /var/www/html/;\n\t\tinternal;\n"
 error_directive="error_page 404 /404.html;\n\t$location_error"
@@ -23,12 +23,17 @@ echo "Hello World!" | sudo tee /var/www/html/index.html
 echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
 
 # Modify the default Nginx site configuration file
-sudo sed -i "s|server_name _;|$new_conf|" /etc/nginx/sites-available/default
-sudo sed -i "0,/}/ s|}|$error_404|" /etc/nginx/sites-available/default
+sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/custom
+sudo sed -i "s|server_name _;|$new_conf|" /etc/nginx/sites-available/custom
+sudo sed -i "0,/}/ s|}|$error_404|" /etc/nginx/sites-available/custom
+sudo ln -s /etc/nginx/sites-available/custom /etc/nginx/sites-enabled/
 
 # Restart Nginx service
 sudo service nginx restart
 
 # Copy the contents of /var/www/html from web-01 to web-02
-ssh ubuntu@web-02 "sudo mkdir -p /var/www/html"
-sudo rsync -avz -e "ssh -o StrictHostKeyChecking=no" /var/www/html/ ubuntu@web-02:/var/www/html/
+if sudo rsync -avz -e "ssh -o StrictHostKeyChecking=no" /var/www/html/ ubuntu@web-02:/var/www/html/; then
+  echo "Files copied successfully"
+else
+  echo "Error copying files" >&2
+fi
